### ISSUE TITLE
patch command for kube-webhook-certgen overrides existing objectSelector

### ISSUE THREAD

**Issue by medyagh** [jet/kube-webhook-certgen#19]
First of all thank you for this great tool !

while reviewing this minikube PR, https://github.com/kubernetes/minikube/pull/8682

I noticed 
```
apiVersion: batch/v1
kind: Job
metadata:
  name: gcp-auth-certs-patch
  namespace: gcp-auth
spec:
  template:
    metadata:
      name: gcp-auth-certs-patch
    spec:
      serviceAccountName: minikube-gcp-auth-certs
      containers:
        - name: patch
          image: jettech/kube-webhook-certgen:v1.2.2
          imagePullPolicy: IfNotPresent
          args:
            - patch
            - --secret-name=gcp-auth-certs
            - --namespace=gcp-auth
            - --patch-validating=false
            - --webhook-name=gcp-auth-webhook-cfg
      restartPolicy: OnFailure
```

will replace the object selector in 

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gcp-auth-webhook-cfg
  labels:
    app: gcp-auth
webhooks:
- name: gcp-auth-mutate.k8s.io
  objectSelector:
    matchExpressions:
      - key: gcp-auth-skip-secret
        operator: NotIn
        values: ["true"]
  sideEffects: None
  admissionReviewVersions: ["v1","v1beta1"]
  clientConfig:
    service:
      name: gcp-auth
      namespace: gcp-auth
      path: "/mutate"
  rules:
  - operations: ["CREATE", "UPDATE"]
```

could this be fixed easily ? maybe by bumping a api version ?
